### ISSUE TITLE
Duplicate lines in plm_buffer_has method

### ISSUE THREAD

**Issue by yasoob** [phoboslab/pl_mpeg#11]
There seem to be some [duplicate lines](https://github.com/phoboslab/pl_mpeg/blob/56a8752909bef43f51a290e9d68d46a59b81f553/pl_mpeg.h#L1552-L1554) in `plm_buffer_has` method:

```
int plm_buffer_has(plm_buffer_t *self, size_t count) {
	if (((self->length << 3) - self->bit_index) >= count) {
		return TRUE;
	}

	if (self->load_callback) {
		self->load_callback(self, self->load_callback_user_data);
	}

	if (((self->length << 3) - self->bit_index) >= count) {
		return TRUE;
	}
	
	if (self->total_size != 0 && self->length == self->total_size) {
		self->has_ended = TRUE;
	}
	return FALSE;
}
```

**Comment by phoboslab** [comment]
This is correct, because the `load_callback()` may be called in between those checks and it may or may not have loaded enough bytes, so we have to check again.

The second check could be moved into the `if (self->load_callback) { ... }` though.
