### ISSUE TITLE
Windows Builds of the PL_MPEG Player

### ISSUE THREAD

**Issue by Zero3K** [phoboslab/pl_mpeg#13]
It would be nice if 32 and 64-bit builds of the player were made available for downloading.

**Comment by Zero3K** [comment]
Can someone please make them?

**Comment by Zero3K** [comment]
Anyone?

**Comment by mrfaptastic** [comment]
This isn't a mpeg1 "player". This is a library that a player would use to decode mpeg1. 

So your question is not valid.

**Comment by Zero3K** [comment]
There's a pl_mpeg_player.c in this repository that functions as a media player which uses the pl_mpeg library.

**Comment by Zero3K** [comment]
Anyone?

**Comment by phoboslab** [comment]
Sorry, no. I don't want to maintain builds for an OS that I don't use. The `pl_mpeg_player.c` serves only as an _example_ on how to use this library.

**Comment by Zero3K** [comment]
How would I go about compiling it?

**Comment by Zero3K** [comment]
I have managed to get it compiled under Windows. I have made a PR with the changes I did to get it compiled. It is #29.
