### ISSUE TITLE
Corrupted video

### ISSUE THREAD

**Issue by matsondawson** [phoboslab/pl_mpeg#17]
When playing video sometimes I get corrupt blocks on the right hand side.
When played in VLC media player it is not corrupted.

See example here: 
![image](https://user-images.githubusercontent.com/1276179/125585510-03ad0be4-7094-418e-9338-5fb1cd069e15.png)

Source file here:
https://www.mdawson.net/files/termcrop.mpg

Frame number 980
I wonder if it's something to do with certain motion blocks on the right hand side?

**Comment by matsondawson** [comment]
It's possible you may not be able to play this with the section in the code labelled "// Make sure we have a full picture in the buffer before attempting to decode it."
It seeks to the next frame to check there is a  full frame (I think).  But it's given me nothing but trouble in the mpegs I've tested.  It usually gets to a point and then seeks to the end of the video.  If I remove it everything works fine.

**Comment by phoboslab** [comment]
This appears to be fixed in https://github.com/phoboslab/pl_mpeg/commit/f0b29241317f149b5be1ba9b6e776f3b51b2827c

Thanks for the test case!
