### ISSUE TITLE
Another segfault found by AFL

### ISSUE THREAD

**Issue by pcwalton** [phoboslab/pl_mpeg#3]
Run through `pl_mpeg_extract_frames` and observe memory corruption.

[bad2.mpg.gz](https://github.com/phoboslab/pl_mpeg/files/3484686/bad2.mpg.gz)

**Comment by phoboslab** [comment]
Fixed with https://github.com/phoboslab/pl_mpeg/commit/46e24ec11ae30ea3788126e5323952c8fedec963 and https://github.com/phoboslab/pl_mpeg/commit/5fe30d90a8a66de1db8e859747c7f9a09ff4cd65
