### ISSUE TITLE
UBSan Triggered

### ISSUE THREAD

**Issue by GithubPrankster** [phoboslab/pl_mpeg#41]
At line 3178:
```c
    else if (motion < ((-fscale) << 4)) {
```
And at line 3366:
```c
    level <<= 1;
```
When using `-fsanitize=undefined`.

Changing these to `else if (motion < (-(fscale << 4))) {` and `level = (int)((unsigned int)level << 1);` seems to work and doesn't present any issues as far as I can tell.

**Comment by phoboslab** [comment]
Fixed with https://github.com/phoboslab/pl_mpeg/pull/43
