### ISSUE TITLE
Interlaced

### ISSUE THREAD

**Issue by padreputativo** [phoboslab/pl_mpeg#44]
I’m using the library through the Defold extension. I’ve used the line from this GitHub to convert the video and updated the library to the latest available version. It looks much better now, but... Is there any way to remove the interlacing that appears? I haven’t seen anything in the code with that name.

**Comment by padreputativo** [comment]
Sorry i forgot to show it

https://github.com/user-attachments/assets/c2e4ee4b-4733-4e84-99fb-f1775aebfbd4

**Comment by phoboslab** [comment]
MPEG1 doesn't support interlacing and neither does this library. Did you convert from an interlaced video to MPEG1? Or is this an interlaced MPEG2 video?

If you can, please provide the output of `ffprobe video.mpg`.

**Comment by padreputativo** [comment]
I’ve tried to remove the interlacing directly from FFmpeg using this line, but it still appears. The curious thing is that it doesn’t show up in any other video player. The only thing I can think of is that Defold itself is somehow adding a shader or something similar. I’ve read something about interlacing in the RGB output of the library...

`ffmpeg -i input.avi -vf yadif -c:v mpeg1video -q:v 0 -an -format mpeg output.mpg`

**Comment by padreputativo** [comment]
I forgot this
![Screenshot from 2024-09-09 22-01-46](https://github.com/user-attachments/assets/5ef6529b-0619-4f1b-be4d-9e84f2e031c3)

**Comment by phoboslab** [comment]
Is the source video interlaced? Or why is the de-interlacing filter (`-yf yadif`) needed? If the source is interlaced – why? I mean, you didn't capture this video from an early 2000s DV camera, I assume!?

This also might be a totally unrelated problem: the stride for the framebuffer might be off. If so you could probably mitigate this by making sure that your video width is a multiple of 8.

Can you try to play the video with the pl_mpeg_player from this repo? Or can you provide the converted video (or a short part of it that exhibits this problem)?

**Comment by padreputativo** [comment]
![image](https://github.com/user-attachments/assets/1f7b55a9-0ea7-43f1-a5fc-043ecf2c0a12)
No, the video is not interlaced. FFmpeg itself shows that. I even converted them to lossless AV1 before MPEG to avoid losing quality. I used that modifier to "guarantee" it wasn't interlaced. As for the resolution, it seems correct, but I’ve come to think it might be a floating-point issue because UV numbers between 0 and 1 are being used. I just tried changing the material, but I didn’t get good results... It’s likely something that Defold is adding.

**Comment by padreputativo** [comment]
https://drive.google.com/file/d/1Mhjp6kZo3aUc0ODsl79do4u5tSXSz1lx/view?usp=sharing

**Comment by phoboslab** [comment]
It's fine in pl_mpeg_player, though there is some aliasing from (I assume) downscaling in the video itself. It looks the same in VLC.

![Screenshot_2024-09-09_22-47-00](https://github.com/user-attachments/assets/8806a911-e4b9-4a91-b102-93278f2aef03)

I'm closing this issue, as it doesn't seem to be a problem with pl_mpeg itself.

**Comment by padreputativo** [comment]
Thank you and sorry for the inconvenience! The artifacts are because it's an AI-generated image, but it looks perfect!
