### ISSUE TITLE
Memory corruption found by AFL

### ISSUE THREAD

**Issue by pcwalton** [phoboslab/pl_mpeg#5]
Running `pl_mpeg_extract_frames` causes memory corruption. AFL found this one too.

[bad3.mpg.gz](https://github.com/phoboslab/pl_mpeg/files/3486607/bad3.mpg.gz)

**Comment by phoboslab** [comment]
Fixed with https://github.com/phoboslab/pl_mpeg/commit/46e24ec11ae30ea3788126e5323952c8fedec963 and https://github.com/phoboslab/pl_mpeg/commit/5fe30d90a8a66de1db8e859747c7f9a09ff4cd65
